version: '3.8'

services:
  nginx:
    image: galshirizli/nginx
    ports:
      - "443:443"  
    networks:
      - my_network
    depends_on:
      - app1
      - app2

  app2:
    image: galshirizli/app2:34
    ports:
      - "3001:3001"  
    networks:
      - my_network

  app1:
    image: galshirizli/app1:34
    ports:
      - "3000:3000"  
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  

